Added support to colored stat nicknames
Seekfried/friedybot-d2irc pull request #9
Opened 2024-07-20 16:50 UTC by nauar

Added support for colored stat nicknames.

IRC:

![image](https://github.com/user-attachments/assets/20c6d685-94c4-47f2-b5e6-ab9e86801645)

DISCORD:

![image](https://github.com/user-attachments/assets/cbe7b9e9-87a4-4eba-a2b6-c9a0f8f2f898)

2024-07-20 17:03 UTC, nauar commented
BTW, the name of the branch does not correspond to the feature implemented :laughing:  My bad

2024-07-22 16:32 UTC, Seekfried requested changes
we don't need the old def get_statsname(self, id) anymore, also is the command_testcolors still needed?

2024-07-22 16:49 UTC, Seekfried commented on friedybot.py
> +            return 1
maybe just my opinion, to make it a little more compact:
```suggestion
        if h < 36:
            return 1
        elif h < 80:
            return 3
        elif h < 150:
            return 2
        elif h < 200:
            return 5
        elif h < 270:
            return 4
        elif h < 330:
            return 6
        else:
            return 1
```
color_thresholds =[(36,1), (80,3), (150,2),(200,5),(270,4),(330,6)]

for theshold, value in color_thresholds:
    if h < threshold:
        return value

return 1

2024-07-22 17:06 UTC, nauar commented
> we don't need the old def get_statsname(self, id) anymore, also is the command_testcolors still needed?

No, I'm sorry. Removing these methods.

2024-07-22 17:10 UTC, merged